services:

  # Socket Server
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "1337:1337"

  # Client
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"  
    
