services:
  # Socket Server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
      - FOO=pbar

  # Client
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_SOCKET_URL="ws://109.234.39.57:1337"
        - FOO="cbar"
        - REACT_APP_FOO="ccbar"
    restart: always
    ports:
      - "443:443"
      - "80:80"
