services:
  # Socket Server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "1337:1337"
    env_file:
      - .env.server.dev

  # Client
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.client.dev
