services:
  # Socket Server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1337:1337"
    # env_file:
    #   - .env.server.prod
    environment:
      - PORT=1337
      - FOO=pbar

  # Client
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
      - "80:80"
    # env_file:
    #   - .env.client.prod
    environment:
      - REACT_APP_SOCKET_URL=http://109.234.39.57:1337
